export const indexTableHead = [{
  prop: 'beginEndAddress',
  text: '区间说明',
  fixed: 'left',
  width: 250
}, {
  prop: 'beginAreaCode',
  text: '寄件区号',
  width: 120
}, {
  prop: 'endAreaCode',
  text: '收件区号',
  width: 235
}, {
  prop: 'surchargeAmount',
  text: '附加费',
  width: 120
}, {
  prop: 'beginWeight',
  text: '起重',
  width: 120
}, {
  prop: 'singleLowestAmount',
  text: '单票最低收费',
  width: 120
}, {
  prop: 'beginTime',
  text: '开始时间',
  width: 120
}, {
  prop: 'endTime',
  text: '结束时间',
  width: 120
}, {
  prop: 'remark',
  text: '备注',
  width: 180
}]
