export const NoticePickup= ()=>import('./notice-pickup.vue')
export const WaybillPush= ()=>import('./waybill-push.vue')
export const ModifyGoodtime=()=>import('./modify-goodtime.vue')
export const UploadOrderFile=()=>import('./upload-order-file.vue')
export const ViewImage=()=>import('./view-image.vue')
export const ViewAllImage=()=>import('./view-all-image.vue')
export const JdAppointment=()=>import('./jd-appointment.vue')
// export const SkuInfo=()=>import('./sku-info.vue')
// export const SuperZone=()=>import('./super-zone.vue')
// export const AddressBookSelect=()=>import('./address-book-select.vue')
export const ParseAddressInfo=()=>import('./parse-address-info.vue')
export const PrintLabel= ()=>import('./print-label.vue')
export const PrintView= ()=>import('./print-view/index.vue')
export const UpdateAppointmentTime=()=>import('./update-appointment-time.vue')
