export const tableColumns = [
  { prop: 'ydNo', text: '运单号', width: '160', visible: true, prohibitSetPosition: true },
  { prop: 'hhDateTime', text: '货好时间', width: '150', visible: true },
  { prop: 'supplierName', text: '供应商', width: '120' },
  { prop: 'ydStatus', text: '运单状态', width: '170', visible: true },
  { prop: 'goods', text: '托寄物', width: '100', visible: true },
  { prop: 'sjCompany', text: '收件公司', width: '150', visible: true },
  { prop: 'sjContactPerson', text: '收件人', width: '100', visible: true },
  { prop: 'uploadTime', text: '创建时间', width: '160', isSort: true },
  { prop: 'sjAddress', text: '收件地址', width: '300', visible: true },
  { prop: 'distance', text: '司机距离我(km)', width: '140' },
  { prop: 'logisticsStatus', text: '物流状态', width: '90' },
  { prop: 'sjMobile', text: '收件手机', width: '120' },
  { prop: 'sjTelephone', text: '收件电话', width: '140' },
  { prop: 'weight', text: '预计重量', width: '90' },
  { prop: 'count', text: '件数', width: '90' },
  { prop: 'serviceWay', text: '服务方式', width: '100' },
  { prop: 'payWay', text: '付款方式', width: '100' },
  { prop: 'payAccount', text: '付款账号', width: '100' },
  { prop: 'totalCost', text: '运费', width: '90' },
  { prop: 'antcipatedFreight', text: '预估运费', width: '90' },
  { prop: 'jjRemark', text: '寄件备注', width: '100' },
  { prop: 'freightWeight', text: '计费重量', width: '90' },
  { prop: 'jjCompany', text: '寄件公司', width: '300' },
  { prop: 'jjContactPerson', text: '寄件人', width: '100' },
  { prop: 'jjDateTime', text: '寄件时间', width: '160', isSort: true },
  { prop: 'sms', text: '寄件手机', width: '150' },
  { prop: 'jjTelePhone', text: '寄件电话', width: '300' },
  // { prop: "backMobile", text: "备用寄件手机", width: "120" },
  { prop: 'qHContactPerson', text: '取货联系人', width: '150' },
  { prop: 'qHContactWay', text: '取货手机', width: '150' },
  { prop: 'qHAddress', text: '寄件地址', width: '120' },
  { prop: 'receiver', text: '签收人', width: '80' },
  { prop: 'receiveDate', text: '签收时间', width: '160', isSort: true },
  { prop: 'proxyStatus', text: '委托书状态', width: '120' },
  { prop: 'vipshopCode', text: '入库号', width: '100' },
  { prop: 'receiptFlag', text: '回单服务', width: '100' }, //TODO:检查字段名称,自定义列
  { prop: 'hdCount', text: '回单份数', width: '100' },
  { prop: 'money', text: '保价声明', width: '100' },
  { prop: 'dsMoney', text: '代收货款', width: '100' },
  { prop: 'mjWay', text: '包装服务', width: '100' },
  { prop: 'sendHouseName', text: '退货仓', width: '100' },
  { prop: 'receiptHouseName', text: '入库仓', width: '100' },
  { prop: 'houseType', text: '仓库类型', width: '100' },
  { prop: 'SizeText', text: '货物尺寸' }
]

export const tableColumns1 = [
  { prop: 'slot', text: '插槽展示', visible: true, defaultSlot: 'column_slot1' },
  { prop: 'slot_button', text: '插槽展示1', visible: true, defaultSlot: 'column_slot2' },
  { prop: 'unDeliveryReason', text: '异常原因', visible: true },
  { prop: 'receiver', text: '签收人', width: '150', visible: true },
  { prop: 'receiveDate', text: '签收时间', width: '150', visible: true },
  { prop: 'waybillNumber', text: '运单号', width: '160', visible: true },
  { prop: 'goodsTime', text: '货好时间', width: '150', visible: true },
  { prop: 'goodsType', text: '托寄物', width: '100', visible: false },
  { prop: 'pickupCompanyName', text: '收件公司', visible: false },
  { prop: 'pickupPerson', text: '收件人', visible: false },
  { prop: 'pickupAddress', text: '收件地址', visible: false }
]

export const migrationTableColumns = [
  { prop: 'id', text: 'ID'},
  { prop: 'waybillNumber', text: '运单号', width: '160', visible: true, },
  { prop: 'failReason', text: '异常原因', width: '150', visible: true },
  { prop: 'pickupCompanyName', text: '收件公司', width: '150', visible: true },
  { prop: 'pickupPerson', text: '收件人', width: '150', visible: true },
  { prop: 'pickupMobile', text: '收件手机', width: '150', visible: true },
  { prop: 'pickupPhone', text: '收件座机', width: '130', visible: true },
  { prop: 'pickupAddress', text: '收件地址', width: '200', visible: true },
  { prop: 'selfSignFlagName', text: '签收要求', width: '150', visible: true },
  { prop: 'deliveryCompanyName', text: '寄件公司', width: '150', visible: true },
  { prop: 'deliveryPerson', text: '寄件人', width: '150', visible: true },
  { prop: 'deliveryMobile', text: '寄件手机', width: '150', visible: true },
  { prop: 'deliveryPhone', text: '寄件座机', width: '150', visible: true },
  { prop: 'deliveryAddress', text: '寄件地址', width: '150', visible: true },
  { prop: 'contactPerson', text: '取货联系人', width: '150', visible: true },
  { prop: 'contactPhone', text: '取货人手机',width: '130', visible: true },
  { prop: 'payModeValue', text: '付款方式', width: '150', visible: true },
  { prop: 'payAccount', text: '付款账号', width: '150', visible: true },
  { prop: 'serviceModeValue', text: '服务方式', width: '150', visible: true },
  { prop: 'goodsType', text: '托寄物', width: '150', visible: true },
  { prop: 'count', text: '件数', width: '120', visible: true },
  { prop: 'weight', text: '重量', width: '120', visible: true },
  { prop: 'preWaybillGoodsSizeListValue', text: '尺寸', width: '120', visible: true },
  { prop: 'declarativeValue', text: '保价声明', width: '150', visible: true },
  { prop: 'collectionAmount', text: '代收货款', width: '150', visible: true },
  { prop: 'woodenFrame', text: '包装服务', width: '150', visible: true },

  { prop: 'receiptFlagValue', text: '回单服务', width: '150', visible: true },
  { prop: 'receiptCount', text: '回单份数', width: '150', visible: true },
  { prop: 'waybillRemark', text: '运单备注', width: '150', visible: true },

  { prop: 'woodenFrameCode', text: '包装服务' },
  { prop: 'selfSignFlag', text: '签收要求'},
  { prop: 'payMode', text: '付款方式'},
  { prop: 'receiptFlag', text: '回单服务'},
  { prop: 'serviceMode', text: '服务方式'},
  { prop: 'preWaybillGoodsSizeList', text: '尺寸'},

  { prop: 'cargoOWner', text: '货主'},
  { prop: 'volume', text: '体积'},
  { prop: 'upstreamNumber', text: '上游单号'},
  { prop: 'type', text: '打印状态'},
  { prop: 'sonyCustomizeds', text: '索尼定制字段'},
]

export const tableColumns2 = [
  { prop: 'slot', text: '插槽展示', visible: true, defaultSlot: 'column_slot1' },
  { prop: 'slot_button', text: '插槽展示1', visible: true, defaultSlot: 'column_slot2' },
  {
    prop: 'waybillNumber',
    text: '运单号',
    width: '160',
    visible: true,
    defaultSlot: 'column_ydNo',
    prohibitHide: true
  },
  { prop: 'goodsTime', text: '货好时间', width: '150', visible: true },
  { prop: 'supplierName', text: '供应商', width: '120', visible: false },
  { prop: 'ydStatus', text: '运单状态', width: '170', visible: true },
  { prop: 'goodsType', text: '托寄物', width: '100', visible: true },
  { prop: 'pickupCustomerName', text: '收件公司', width: '150', visible: true },
  { prop: 'pickupPerson', text: '收件人', width: '100', visible: true },
  // { prop: 'uploadTime', text: '创建时间', width: '160', visible: false, isSort: true },
  { prop: 'pickupAddress', text: '收件地址', width: '300', visible: true },
  // { prop: 'distance', text: '司机距离我(km)', width: '140', visible: false },
  { prop: 'logisticsStatus', text: '物流状态', width: '90', visible: false },
  { prop: 'pickupMobile', text: '收件手机', width: '120', visible: false },
  { prop: 'pickupPhone', text: '收件电话', width: '140', visible: false },
  { prop: 'actualWeight', text: '预计重量', width: '90', visible: false },
  { prop: 'count', text: '件数', width: '90', visible: false },
  { prop: 'serviceModeDesc', text: '服务方式', width: '100', visible: false },
  { prop: 'payModeDesc', text: '付款方式', width: '100', visible: false },
  { prop: 'payAccount', text: '付款账号', width: '100', visible: false },
  { prop: 'totalCost', text: '运费', width: '90', visible: false },
  { prop: 'antcipatedFreight', text: '预估运费', width: '90', visible: false },
  { prop: 'jjRemark', text: '寄件备注', width: '100', visible: false },
  { prop: 'freightWeight', text: '计费重量', width: '90', visible: false },
  { prop: 'deliveryCustomerName', text: '寄件公司', width: '300', visible: false },
  { prop: 'deliveryPerson', text: '寄件人', width: '100', visible: false },
  { prop: 'jjDateTime', text: '寄件时间', width: '160', visible: false, isSort: true },
  { prop: 'deliveryMobile', text: '寄件手机', width: '150', visible: false },
  { prop: 'deliveryPhone', text: '寄件电话', width: '300', visible: false },
  { prop: 'qHContactPerson', text: '取货联系人', width: '150', visible: false },
  { prop: 'qHContactWay', text: '取货手机', width: '150', visible: false },
  { prop: 'deliveryAddress', text: '寄件地址', width: '120', visible: false },
  { prop: 'receiver', text: '签收人', width: '80', visible: false },
  { prop: 'receiveTime', text: '签收时间', width: '160', visible: false, isSort: true },
  { prop: 'proxyStatus', text: '委托书状态', width: '120', visible: false },
  { prop: 'productCode', text: '入库号', width: '100', visible: false },
  { prop: 'receiptFlag', text: '回单服务', width: '100', visible: false }, //TODO:检查字段名称,自定义列
  { prop: 'receiptCount', text: '回单份数', width: '100', visible: false },
  { prop: 'insuranceValue', text: '保价声明', width: '100', visible: false },
  { prop: 'collectAmount', text: '代收货款', width: '100', visible: false },
  { prop: 'woodenFrameFlagDesc', text: '包装服务', width: '100', visible: false },
  { prop: 'inWareHouseName', text: '退货仓', width: '100', visible: false },
  { prop: 'inWareHouseName', text: '入库仓', width: '100', visible: false },
  { prop: 'inWareHouseType', text: '仓库类型', width: '100', visible: false },
  { prop: 'SizeText', text: '货物尺寸', width: '100', visible: false }
]

export const encryptFields = [
  'jjContactPerson',
  'sms',
  'jjTelePhone',
  'qHAddress',
  'qHContactPerson',
  'qHContactWay',
  'sjContactPerson',
  'sjMobile',
  'sjTelephone',
  'sjAddress'
]

export function getTableColumns() {
  return JSON.parse(JSON.stringify(tableColumns2))
}

export function getEncryptFields() {
  return JSON.parse(JSON.stringify(encryptFields))
}

export function getData() {
  return [
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '2009150be026446b80be88cad8f71651',
      waybillNumber: 'KY8000010046286',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '测试',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜1',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '4.39',
      count: '80',
      serviceMode: '10',
      serviceModeValue: '当天达',
      payMode: '10',
      payModeValue: '寄方付',
      payAccount: '02109242168',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '上海壹墨',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '0762-6536523',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '',
      declarativeValue: '100.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '京东',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/17 10:32:42',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '4d14beee1bd94edcbbb6c3c84c61bfc3',
      waybillNumber: 'KY1000120038386',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '托寄物',
      pickupCompanyName: '广州跨越',
      pickupPerson: '李四',
      pickupAddress: '广东省广州市花都区花东镇',
      pickupAddressEn: '',
      pickupMobile: '18888888889',
      pickupPhone: '0755-23232111-001',
      weight: '',
      count: '',
      serviceMode: '50',
      serviceModeValue: '同城次日',
      payMode: '10',
      payModeValue: '寄方付',
      payAccount: '075517017608',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: '',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '介绍的',
      deliveryPerson: '张三',
      deliveryTime: '',
      deliveryMobile: '13888888888',
      deliveryPhone: '0755-23232111-001',
      deliveryAddress: '广东省广州市花都区花东镇',
      contactPerson: '王五',
      contactPhone: '13999999999',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'True',
      receiptFlag: '10',
      receiptCount: '1',
      declarativeValue: '',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/16 22:26:11',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '',
      agentCode: null,
      destAirport: '广州',
      destOperDepart: '花东取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华南',
      pickupAreaCode: '020',
      firstAllocationAName: '花东机场分拨',
      receiptDepotAllName: '九一点部',
      zoneName: '',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '45f680e474a24befb7067487d2ffb855',
      waybillNumber: 'KY8000010042572',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '鞋子/衣服',
      pickupCompanyName: '湖北蜂窝板',
      pickupPerson: '陈红润',
      pickupAddress: '湖北省黄冈市红安县觅儿寺镇',
      pickupAddressEn: '',
      pickupMobile: '18211111111',
      pickupPhone: '15171624237',
      weight: '10.00',
      count: '',
      serviceMode: '220',
      serviceModeValue: '专运',
      payMode: '10',
      payModeValue: '寄方付',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: '',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '介绍的',
      deliveryPerson: '阿拉巴巴',
      deliveryTime: '',
      deliveryMobile: '18888888889',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永大洋公司第二生活区',
      contactPerson: '阿拉巴巴',
      contactPhone: '18888888889',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '30',
      receiptCount: '1',
      declarativeValue: '5000.00',
      collectionAmount: '',
      woodenFrame: '打木架',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/13 16:38:18',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '',
      destOperDepart: '',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '',
      pickupAreaCode: '0713',
      firstAllocationAName: '',
      receiptDepotAllName: '',
      zoneName: '',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '722253fca728430fb502192290830ce8',
      waybillNumber: 'KY8000010042569',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '鞋子/衣服',
      pickupCompanyName: '湖北蜂窝板',
      pickupPerson: '陈红润',
      pickupAddress: '湖北省黄冈市红安县觅儿寺镇',
      pickupAddressEn: '',
      pickupMobile: '18211111111',
      pickupPhone: '15171624237',
      weight: '10.00',
      count: '',
      serviceMode: '220',
      serviceModeValue: '专运',
      payMode: '10',
      payModeValue: '寄方付',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: '',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '介绍的',
      deliveryPerson: '阿拉巴巴',
      deliveryTime: '',
      deliveryMobile: '18888888889',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永大洋公司第二生活区',
      contactPerson: '阿拉巴巴',
      contactPhone: '18888888889',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '',
      declarativeValue: '5000.00',
      collectionAmount: '',
      woodenFrame: '打木架',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/13 16:35:23',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '',
      destOperDepart: '',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '',
      pickupAreaCode: '0713',
      firstAllocationAName: '',
      receiptDepotAllName: '',
      zoneName: '',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '7c1fe59be1b1464bb45e39d63dc97f25',
      waybillNumber: 'KY1000120027779',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜2',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '3.21',
      count: '250',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '20',
      payModeValue: '收方付',
      payAccount: '083766362858',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01:
        'FL21040784111111111w1,FL21040784111111111w2,FL210407841111111113,FL21040784111111111w4,FL21040784111111111w5',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/10 11:41:51',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '1b979dbd65844d7db0fa842526ae6a02',
      waybillNumber: 'KY1000120027778',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜1',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '4.39',
      count: '80',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '10',
      payModeValue: '寄方付月结',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/10 11:41:51',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: 'd9cfb71d8d53440cbfbec5b5f03e550e',
      waybillNumber: 'KY1000120027777',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '4.39',
      count: '',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '10',
      payModeValue: '寄方付月结',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/10 11:41:51',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: '7dde96341aa54b0484dda6697e525394',
      waybillNumber: 'KY8000010040027',
      goodsTime: null,
      printStatus: '是',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜2',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '3.21',
      count: '250',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '20',
      payModeValue: '收方付',
      payAccount: '083766362858',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01:
        'FL21040784111111111w1,FL21040784111111111w2,FL210407841111111113,FL21040784111111111w4,FL21040784111111111w5',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/9 20:17:14',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: 'c6483e8711ae4a92b5bea9e6f7344389',
      waybillNumber: 'KY8000010040026',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜1',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '4.39',
      count: '80',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '10',
      payModeValue: '寄方付月结',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/9 20:17:14',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    },
    {
      waybillStatus: '待通知取货',
      waybillCustomerSource: 10,
      id: 'ac26150aba55459ab168f7d5c3d76039',
      waybillNumber: 'KY8000010040025',
      goodsTime: null,
      printStatus: '否',
      printTimes: 0,
      goodsType: '[货物名称(数量+单位)];',
      pickupCompanyName: '',
      pickupPerson: '李丽丽',
      pickupAddress: '浙江省杭州市上城区延安南路98号B1楼FILA专柜',
      pickupAddressEn: '',
      pickupMobile: '15068257587',
      pickupPhone: '',
      weight: '4.39',
      count: '',
      serviceMode: '20',
      serviceModeValue: '次日达',
      payMode: '10',
      payModeValue: '寄方付月结',
      payAccount: '',
      estimatedFreight: '',
      freightAmount: '',
      waybillRemark: 'FLOD2105270429',
      customColumnValue_01: '',
      customColumnValue_02: '',
      customColumnValue_03: '',
      deliveryCompanyName: '南方益利韺公司',
      deliveryPerson: '芭芭拉',
      deliveryTime: '',
      deliveryMobile: '18888888888',
      deliveryPhone: '',
      deliveryAddress: '广东省深圳市宝安区福永街道第七专职消防队',
      contactPerson: '芭芭拉',
      contactPhone: '18888888888',
      receiver: null,
      receiveDate: null,
      receiptStatus: 'False',
      receiptFlag: '20',
      receiptCount: '0',
      declarativeValue: '27750.00',
      collectionAmount: '',
      woodenFrame: '',
      deliveryWareHouseName: '',
      pickupWareHouseName: '',
      selfSignFlag: false,
      hadOrder: '',
      uploadTime: '2021/9/9 20:17:14',
      preWaybillGoodsSizeList: [],
      couponPrizeCode: '',
      couponPrizeDesc: '',
      orderNumber: '',
      cargoStorageStatus: 0,
      goodsInfo: '',
      vipshopCode: '',
      insuranceValueSource: '20',
      agentCode: null,
      destAirport: '台州',
      destOperDepart: '台州取派部',
      transferType: 0,
      targetSortCenterName: null,
      originNodeName: null,
      JDCode: null,
      transportType: null,
      productType: null,
      destinationCrossCode: null,
      destinationTabletrolleyCode: null,
      temperatureType: null,
      siteId: null,
      siteName: null,
      road: null,
      targetSortCenterId: null,
      cityShortCode: null,
      cpShortCode: null,
      originNodeCode: null,
      destinationNodeWaterCode: null,
      outboundAllocation: '',
      regionCode: '华东',
      pickupAreaCode: '0571',
      firstAllocationAName: '台州中转场',
      receiptDepotAllName: '新城点部',
      zoneName: 'D区',
      viewBarCode: null,
      freightWeight: 0.0
    }
  ]
}

export function getPageList() {
  return [
    {
      actualWeight: 1,
      chargeType: 0,
      collectAmount: 3,
      companyReceivable: 10,
      count: 3,
      deliveryAddress: '航城街道航站四路',
      deliveryAreaCode: '0755',
      deliveryCity: '深圳市',
      deliveryMobile: '18888888889',
      deliveryPerson: '张三寄',
      deliveryPhone: '0755-2365412',
      deliveryProvince: '广东省',
      deliveryCustomerName: '深圳仁美',
      freightWeight: 2,
      goodsTime: '2021-09-29 10:23:40',
      goodsType: '水果',
      inWareHouseName: '收方仓库-京东',
      inWareHouseType: 1,
      insuranceValue: 200,
      orderNumber: '',
      orderRemark: '寄件备注',
      orderStatus: 2,
      outWareHouseName: '寄方仓库-唯品会',
      payMode: 3,
      paymentCustomer: '付款公司-跨越',
      pickupAddress: '布吉街道布龙路10号',
      pickupAreaCode: '0762',
      pickupCity: '河源市',
      pickupCustomerName: '收件公司-收',
      pickupMobile: '18588886542',
      pickupPhone: '0762-3654256',
      pickupProvince: '广东省',
      pickupPerson: '收件人-小李',
      deliveryTime: '2021-09-30 11:20:30',
      printFlag: '已打印',
      productCode: '入库号3335698556-5523',
      receiptCount: 1,
      receiptFlag: 3,
      receiveTime: 595,
      receiver: 'nsjn',
      selfSufficiencyBranchAddress: '自提地址-深圳市',
      serviceMode: '当天达',
      waybillNumber: 'KY1000000001298',
      waybillRemark: '运单备注-帮我打木架',
      waybillStatus: 1,
      woodenFrameFlag: 0,
      canNeedPay: 0,
      storageFeeStatus: 2,
      canExpediting: 0,
      scoreStatus: 0,
      scoreQueryStatus: 2,
      scoreModifyStatus: 0,
      canAnotherOrder: 3,
      hasDeliveryCode: 2,
      hasSelfMention: 2,
      hasCustomerService: 0,
      canTake: 0
    },
    {
      actualWeight: 1,
      chargeType: 0,
      collectAmount: 3,
      companyReceivable: 10,
      count: 3,
      deliveryAddress: '航城街道航站四路',
      deliveryAreaCode: '0755',
      deliveryCity: '深圳市',
      deliveryMobile: '18888888889',
      deliveryPerson: '张三寄',
      deliveryPhone: '0755-2365412',
      deliveryProvince: '广东省',
      deliveryCustomerName: '深圳仁美',
      freightWeight: 2,
      goodsTime: '2021-09-29 10:23:40',
      goodsType: '水果',
      inWareHouseName: '收方仓库-京东',
      inWareHouseType: 1,
      insuranceValue: 200,
      orderNumber: '',
      orderRemark: '寄件备注',
      orderStatus: 2,
      outWareHouseName: '寄方仓库-唯品会',
      payMode: 3,
      paymentCustomer: '付款公司-跨越',
      pickupAddress: '布吉街道布龙路10号',
      pickupAreaCode: '0762',
      pickupCity: '河源市',
      pickupCustomerName: '收件公司-收',
      pickupMobile: '18588886542',
      pickupPhone: '0762-3654256',
      pickupProvince: '广东省',
      pickupPerson: '收件人-小李',
      deliveryTime: '2021-09-30 11:20:30',
      printFlag: '已打印',
      productCode: '入库号3335698556-5523',
      receiptCount: 1,
      receiptFlag: 3,
      receiveTime: 595,
      receiver: 'nsjn',
      selfSufficiencyBranchAddress: '自提地址-深圳市',
      serviceMode: '当天达',
      waybillNumber: 'KY0000124526814',
      waybillRemark: '运单备注-帮我打木架',
      waybillStatus: 1,
      woodenFrameFlag: 0,
      canNeedPay: 0,
      storageFeeStatus: 2,
      canExpediting: 0,
      scoreStatus: 0,
      scoreQueryStatus: 2,
      scoreModifyStatus: 0,
      canAnotherOrder: 3,
      hasDeliveryCode: 2,
      hasSelfMention: 2,
      hasCustomerService: 0,
      canTake: 0
    }
  ]
}

/*
  运单查询结果字段转换
*/
const receiptFlags = {
  10: '回单原件',
  20: '无',
  30: '回单图片',
  40: '电子回单',
}
export function convertQueryModels(waybills) {
  if (!waybills) {
    return []
  }
  const result = waybills.map(val => {
    // val.preWaybillGoodsSizeList = [
    //   {
    //     count: "1",
    //     height: "2.00",
    //     length: "3.00",
    //     width: "4.00",
    //   },
    //   {
    //     count: "0",
    //     height: "0.00",
    //     length: "1.00",
    //     width: "2.00",
    //   },
    //   {
    //     count: "0",
    //     height: "0.00",
    //     length: "0.00",
    //     width: "0.00",
    //   }
    // ]
    const sizeList = []
    const preWaybillGoodsSizeList = val.preWaybillGoodsSizeList.map(sizeItem => {
      let arr = []
      if (+sizeItem.length <= 0) {
        sizeItem.length = ''
      } else {
        arr.push(sizeItem.length)
      }
      
      if (+sizeItem.width <= 0) {
        sizeItem.width = ''
      } else {
        arr.push(sizeItem.width)
      }

      if (+sizeItem.height <= 0) {
        sizeItem.height = ''
      } else {
        arr.push(sizeItem.height)
      }

      if (+sizeItem.count <= 0) {
        sizeItem.count = ''
      } else {
        arr.push(sizeItem.count)
      }
      const result = arr.join('*')
      if (result) {
        sizeList.push(result)
      }
      return sizeItem
    })

    const item = {
      /** 数据ID */
      id: val.id,
      waybillNumber: val.waybillNumber,
      failReason: val.failReason,
      pickupCompanyName: val.pickupCompanyName,
      pickupPerson: val.pickupPerson,
      pickupMobile: val.pickupMobile,
      pickupPhone: val.pickupPhone,
      pickupAddress: val.pickupAddress,
      selfSignFlagName: val.selfSignFlag ? '是' : '否',
      selfSignFlag: val.selfSignFlag,
      deliveryCompanyName: val.deliveryCompanyName,
      deliveryPerson: val.deliveryPerson,
      deliveryMobile: val.deliveryMobile,
      deliveryPhone: val.deliveryPhone,
      deliveryAddress: val.deliveryAddress,
      contactPerson: val.contactPerson,
      contactPhone: val.contactPhone,
      payMode: val.payMode,
      payModeValue: val.payModeValue,
      payAccount: val.payAccount,
      serviceModeValue: val.serviceModeValue,
      serviceMode: val.serviceMode,
      goodsType: val.goodsType,
      count: val.count,
      weight: val.weight,
      preWaybillGoodsSizeListValue: sizeList.length > 0 ? sizeList : '',
      preWaybillGoodsSizeList: preWaybillGoodsSizeList,
      declarativeValue: val.declarativeValue,
      collectionAmount: val.collectionAmount,
      woodenFrame: val.woodenFrame,
      woodenFrameCode: val.woodenFrameCode,
      receiptFlagValue: receiptFlags[val.receiptFlag] || '',
      receiptFlag: val.receiptFlag,
      receiptCount: val.receiptCount <= 0 ? '' : val.receiptCount,
      waybillRemark: val.waybillRemark,
      declaredValue: val.declaredValue,
      vipshopCode: val.vipshopCode,
      customColumnValue_01: val.customColumnValue_01,
      customColumnValue_02: val.customColumnValue_02,
      customColumnValue_03: val.customColumnValue_03,
      cargoOWner: val.cargoOWner,
      volume: val.volume,
      upstreamNumber: val.upstreamNumber,
      type: val.type,
      sonyCustomizeds: val.sonyCustomizeds,
      insuranceValueSource: val.insuranceValueSource,
      sendHouseName: val.sendHouseName,
      deliveryWareHouseName: val.deliveryWareHouseName,
      pickupWareHouseName: val.pickupWareHouseName,
      houseType: val.houseType,
      deliveryModel: val.deliveryModel,
      shortCompany: val.shortCompany,
    }
    return item
  })
  return result
}

