export const UploadOrderFile = () => import('./upload-order-file.vue')
export const WaybillInfo = () => import('./waybill-info.vue')
export const WaybillRouter = () => import('./waybill-router.vue')
export const WaybillState = () => import('./waybill-state.vue')
export const PrintLabel = () => import('./print-label.vue')
export const SignedImage = () => import('./waybill-detail-signed-image.vue')
export const WaybillDetailMaterial = () => import('./waybill-detail-material.vue')
